### PR TITLE
Turn off mtest06/mmap3 because it may consume too much memory

### PR DESCRIPTION
**Pull request by kolerov**
As it said in test's comments it may consume up to 1GB of memory. Thus it's capable to hang Linux (and sometimes it does in case of AXS101 board).

### CODE REVIEW

**Comment by vineetgarc** [comment]
if it's oom (out of memory) Linux already handles it well - culprit task is nuked. A hang means something is broken either in kernel or userspace - sometimes in the test itself.
AXS101 clocks at pretty high frequency so slowness shd not be an issue

**Comment by kolerov** [comment]
I'll try to investigate it properly then. By the way I've noticed that most hangs occurs in multi-threaded tests.

**Comment by anthony-kolesov** [comment]
If linux doesn't abort this test when it runs out of memory, then this could be because this is mmap. So it should create a file, I guess? And that file should be 1GiB. So perhaps issue with that big file.  This is just speculation, not really a theory. 

Also perhaps you can make this a dynamic check, instead of just disabling test, testframework will check if necessary requirements are met in will abort test if they are not. But first task is to figure out why exactly test hangs.

**Comment by kolerov** [comment]
This test passes on the latest Linux. Close this PR.

**Comment by vineetgarc** [comment]
@dr-hannibal  Weird ! Per latest update on 9000939393 RANKED B2|Linux sometimes hangs on LTP's mmap3 test - it still seems to test - what platform did u check it - Can you please sync up with Eugeniy on the topic !

**Comment by kolerov** [comment]
@vineetgarc I have forgotten that this error occurs just sometimes. I have checked it once on HS38 and it worked fine. Open it again for further investigation.

**Pull request closed without merging**
